language: python
python:
- '3.6'
install:
- pip install -r ./requirements.txt
script:
- mkdocs build
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_da3f986a3a02_key -iv $encrypted_da3f986a3a02_iv
  -in tinyfat-jap.pem.enc -out \/tmp\/id_rsa -d
- chmod 600 /tmp/id_rsa
- echo -e "Host 47.74.46.113\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- ssh -i /tmp/id_rsa root@47.74.46.113 'cd /home/blog && ./update.sh'
